#! /usr/bin/env zsh

PROJECT_NAME=$1
DATA_STRING="{\"name\":\"$PROJECT_NAME\",\"private\":false}"
curl -u "mkuzmick:$GITHUB_TOKEN" https://api.github.com/user/repos -d $DATA_STRING
code $PROJECT_NAME
cd $PROJECT_NAME
git remote add origin "https://github.com/mkuzmick/$PROJECT_NAME.git"
git branch -M main
git push -u origin main