#! /usr/bin/env zsh

echo "mk resource starting up"

THEDATE=$(date '+%Y%m%d')
THEDATE_FOR_YAML=$(date '+%Y-%m-%d')
THETIME=$(date '+%H%M%S')
RESOURCE_PATH="/Users/mk/Development/mk-show/content/shows/mk/resources/$1-$THEDATE.md"
# SHOW_TEMPLATE_PATH="../../../mk-show/content/documentation/mk-show-template.md"
RESOURCE_TEMPLATE="---
title: $1-$THEDATE
author: Marlon Kuzmick
mainImage: https://upload.wikimedia.org/wikipedia/commons/9/91/Blacksmith_tools_2.jpg
date: $THEDATE_FOR_YAML
tools: []
---
# $1

$THEDATE.$THETIME

 mk start


"

if [[ -f $RESOURCE_PATH ]]
    then
        echo "$RESOURCE_PATH exists"
        # open -a FoldingText $RESOURCE_PATH
        code $RESOURCE_PATH
        # open -a "nvUltra Beta" $SHOW_PATH
        # open -a "Marked 2" $WORKBOOK_PATH
    else
        echo "starting $RESOURCE_PATH"
        echo $RESOURCE_TEMPLATE >> $RESOURCE_PATH

        # open -a "nvUltra Beta" $SHOW_PATH
        # open -a FoldingText $RESOURCE_PATH
        # open -a "Marked 2" $RESOURCE_PATH
        code $RESOURCE_PATH
fi
